/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/appusers` | `/appusers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/companies` | `/companies`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/discounts` | `/discounts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/pricing` | `/pricing`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/vehicles` | `/vehicles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/washers` | `/washers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/new-record` | `/new-record`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/appusers` | `/appusers`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/companies` | `/companies`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/discounts` | `/discounts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/pricing` | `/pricing`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/vehicles` | `/vehicles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/washers` | `/washers`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/new-record` | `/new-record`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/appusers${`?${string}` | `#${string}` | ''}` | `/appusers${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/companies${`?${string}` | `#${string}` | ''}` | `/companies${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/discounts${`?${string}` | `#${string}` | ''}` | `/discounts${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/pricing${`?${string}` | `#${string}` | ''}` | `/pricing${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/vehicles${`?${string}` | `#${string}` | ''}` | `/vehicles${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/washers${`?${string}` | `#${string}` | ''}` | `/washers${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/new-record${`?${string}` | `#${string}` | ''}` | `/new-record${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/appusers` | `/appusers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/companies` | `/companies`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/discounts` | `/discounts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/pricing` | `/pricing`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/vehicles` | `/vehicles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/washers` | `/washers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/new-record` | `/new-record`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
